name: AreaSpawnLite
version: 1.0
main: com.popupmc.areaspawnlite.AreaSpawnLite
description: Area Spawn Lite
author: junebug12851
api-version: 1.16

commands:
  travel:
    description: Travels
    usage: /travel <player>
  asl:
    description: Area Spawn Lite Admin
    usage: /asl
    permission: asl.use
    permission-message: You do not have permission to use Area Spawn Lite Management

permissions:
  asl.use:
    description: Allows you to manage Area Spawn Lite
    default: op
